name: Update KP Index

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

- name: Try primary NOAA source, fallback to alternative
  run: |
    set -x
    echo "📡 Пробуем основной источник NOAA..."
    STATUS=$(curl -s -w "%{http_code}" -o tmp_primary.json https://services.swpc.noaa.gov/json/planetary_k_index.json)

    if [ "$STATUS" = "200" ] && jq empty tmp_primary.json 2>/dev/null; then
      echo "✅ Основной источник работает. Сохраняем..."
      jq -c '.[-1]' tmp_primary.json > docs/planetary_k_index.json
    else
      echo "⚠️ Основной источник не доступен. Код: $STATUS. Пробуем альтернативу..."
      curl -s https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json -o tmp_alt.json
      jq -c '.[-1]' tmp_alt.json > docs/planetary_k_index.json
      echo "✅ Альтернативный источник использован."
    fi

          echo "📄 Содержимое сохранённого файла:"
          cat docs/planetary_k_index.json

      - name: Commit and push
        run: |
          git config user.name "GitHub Action"
          git config user.email "actions@github.com"
          git status
          ls -l docs/
          git add docs/planetary_k_index.json
          git commit -m "Update KP index from available NOAA source" || echo "ℹ️ Нет изменений для коммита"
          git push
